### ISSUE TITLE
are there API for create/update/delete file?

### ISSUE THREAD

**Issue by lonfee88** [gmessner/gitlab-api#6]
API for http://doc.gitlab.com/ce/api/repository_files.html

**Comment by gmessner** [comment]
These have not yet been implemented.  I plan on implementing them in a few days (over the weekend).  However if you would like to add these to you previous pull request I would be happy to merge your work.

Please pull the latest code as it has just had a major update.

Thanks again for your contributions,
Greg

**Comment by lonfee88** [comment]
I have add those API in my previous pull request :)

**Comment by gmessner** [comment]
Thank you for adding these calls. 

I have completed the merge and have push the new version to Maven Central.
